info:
  name: ProductCreateDto
  type: http
  seq: 6

http:
  method: POST
  url: http://f1.example.com/products/test
  body:
    type: json
    data: |-
      {
        "img": "6e041d9d0fdc79b37f029c4eb948953e",
        "name": "测试名称",
        "summary": "测试简介",
        "options": [
          { "foo": 1 }
        ]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
